### ISSUE TITLE
FQ-U-GAT-IT pytorch

### ISSUE THREAD

**Issue by Decalogue** [YangNaruto/FQ-GAN#7]
Great work!
Could you release the pytorch version of  FQ-U-GAT-IT?
Thank you so much!

**Comment by ChunyuanLI** [comment]
In our experiments, we found that it is difficult to reproduce the good results using the PyTorch version of baseline method U-GAT-IT (https://github.com/znxlwm/UGATIT-pytorch), as observed by others on [Reddit](https://www.reddit.com/r/MachineLearning/comments/g2l1us/r_unsupervised_imagetoimage_translation_turns/?%24deep_link=true&correlation_id=eca2cbf1-6aa8-4387-a0b8-8f9781d9b4d5&ref=email_digest&ref_campaign=email_digest&ref_source=email&utm_content=post_title&utm_medium=digest&utm_name=top_posts&utm_source=email&utm_term=day&%243p=e_as&%24original_url=https%3A%2F%2Fwww.reddit.com%2Fr%2FMachineLearning%2Fcomments%2Fg2l1us%2Fr_unsupervised_imagetoimage_translation_turns%2F%3F%24deep_link%3Dtrue%26correlation_id%3Deca2cbf1-6aa8-4387-a0b8-8f9781d9b4d5%26ref%3Demail_digest%26ref_campaign%3Demail_digest%26ref_source%3Demail%26utm_content%3Dpost_title%26utm_medium%3Ddigest%26utm_name%3Dtop_posts%26utm_source%3Demail%26utm_term%3Dday&_branch_match_id=762407484753216397) as well. That's why we did not release this version.

**Comment by Decalogue** [comment]
Thank you!
